### ISSUE TITLE
Can not convert Caffe model to theano 

### ISSUE THREAD

**Issue by jompojw** [piergiaj/caffe-to-theano#1]
Im  beginner in caffe and I want to convert caffe model to theano mode and this it the result 

```
 `jmj@img-01:~/caffe-to-theano-master$ python caffe_to_theano.py lenet_train_test.prototxt mnist_iter_500000.caffemodel 
/usr/local/lib/python2.7/dist-packages/theano/tensor/signal/downsample.py:6: UserWarning: downsample module has been moved to the theano.tensor.signal.pool module.
  "downsample module has been moved to the theano.tensor.signal.pool module.")
Using gpu device 0: Tesla K20m (CNMeM is disabled, CuDNN not available)
loading structure from lenet_train_test.prototxt
loading data from mnist_iter_500000.caffemodel
Traceback (most recent call last):
  File "caffe_to_theano.py", line 47, in <module>
    in_size = [batch_size, net_param.input_dim[1], net_param.input_dim[2], net_param.input_dim[3]]
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/internal/containers.py", line 64, in __getitem__
    return self._values[key]
IndexError: list index out of range` 

```

what should I do ?

**Comment by ciychen** [comment]
@Boltfox I met the same issue as you. Looks like this repo was abandoned for a long time.
